### PR TITLE
Fixes #31575 - Online and offline backup with --include-db-dumps fails

### PR DESCRIPTION
**Pull request by ianballou**
This fixes a syntax error that was failing online and offline backups.

### CODE REVIEW

**Comment by jturel** [comment]
Works for me! Does it really relate to offline backups as well? To me it only seems like online.

**Comment by ianballou** [comment]
> Works for me! Does it really relate to offline backups as well? To me it only seems like online.

Looks like `Procedures::Backup::Online::SafetyConfirmation` is used for offline backups as well if `--include-db-dumps` is present: https://github.com/theforeman/foreman_maintain/blob/master/definitions/scenarios/backup.rb#L122

**Comment by jturel** [comment]
> > Works for me! Does it really relate to offline backups as well? To me it only seems like online.
> 
> Looks like `Procedures::Backup::Online::SafetyConfirmation` is used for offline backups as well if `--include-db-dumps` is present: https://github.com/theforeman/foreman_maintain/blob/master/definitions/scenarios/backup.rb#L122

Sorry, I got that the wrong way around!

```
[root@newhost certs]# foreman-maintain backup online --include-db-dumps /tmp                                            
ERROR: Unrecognised option '--include-db-dumps'
```

ACK in any case :)

**Review by jturel — APPROVED** [review]
ACK

**Review by upadhyeammit — APPROVED** [review]

**Pull request merged**
