### PR TITLE
Fixes #20604 - katello-service feature to make services start/stop

### PR DESCRIPTION
**Pull request by kgaikwad**

### CODE REVIEW

**Comment by swapab** [comment]
I think we already have a `katello` feature here https://github.com/theforeman/foreman_maintain/pull/69
I'll rebase the PR and update accordingly.

@kgaikwad You may have a look and see if it meets the purpose?

**Comment by kgaikwad** [comment]
@swapab ,

I have already added `katello-service` feature in qpidd PR.
Could you please check PR [#52](https://github.com/theforeman/foreman_maintain/pull/52).

We have some queries related to PR #52 that's why I marked it as `On-Hold`.
To unblock other PRs, I have separated out the code into this new PR.

**Comment by kgaikwad** [comment]
@swapab , 

One more thing I forgot to mention here is that `katello` & `katello-service` are two different things.
`katello` is plugin and `katello-service` comes under katello-packaging using which we can perform actions like `start/stop/status` for few services. So we can't mix these two.

**Comment by swapab** [comment]
@kgaikwad Got it.

I think it would be sensible to add `katello-service` under `definition/services/`

**Comment by iNecas** [comment]
Based on scrum call discussion, I'm ok with leaving this one as is and not introducing another namespace for now. Thanks @kgaikwad

**Pull request merged**
