### PR TITLE
Fixes #22244 - Skip whitelisted steps

### PR DESCRIPTION
**Pull request by swapab**

### CODE REVIEW

**Comment by iNecas** [comment]
Besides the rubocop failures, probably related to new rubocop version (which I will separate PR against), the tests are failing https://travis-ci.org/theforeman/foreman_maintain/jobs/350254122

**Comment by iNecas** [comment]
Besides the rubocop failures, probably related to new rubocop version (which I will separate PR against), the tests are failing https://travis-ci.org/theforeman/foreman_maintain/jobs/350254122

**Comment by iNecas** [comment]
@ntkathole mind testing?

**Comment by swapab** [comment]
Failing test case fixed. https://travis-ci.org/theforeman/foreman_maintain/jobs/350286433
Moved the check of `skipped?` from `execution.rb` to `executable.rb`

**Comment by iNecas** [comment]
Approved code-wise, Waiting for QE blessing.

**Comment by ntkathole** [comment]
Looks good ! Just a nickpick in help option
`-w, --whitelist whitelist     Comma-separated list of labels of steps to be ignored`
Replace ignored with skipped.

**Comment by iNecas** [comment]
Needs rebase

**Comment by swapab** [comment]
Rebase.
@ntkathole `--whitelist` description has been updated.

**Comment by iNecas** [comment]
Thanks @swapab and @ntkathole

**Pull request merged**
