### PR TITLE
Fixes #33281 - run installer with upgrade flags after restore

### PR DESCRIPTION
**Pull request by evgeni**

### CODE REVIEW

**Comment by jlsherrill** [comment]
the rake task can also be useful for zstreams (if you're restoring on a newer z-stream sometimes upgrade steps are added to resolve issues).  But it should be run with this change. 

I don't know that comparing versions is worth the headache to save a single installer run

**Comment by evgeni** [comment]
@jlsherrill `upgrade:run` is executed for Katello as part of an installer run, but not Satellite.

**Comment by jlsherrill** [comment]
@evgeni does anything run it as part of satellite?

**Comment by evgeni** [comment]
`foreman-maintain upgrade …` does run it, yes.

**Comment by jlsherrill** [comment]
looks good to me!

**Review by jlsherrill — APPROVED** [review]

**Pull request merged**
