### PR TITLE
Fixed - Config related to packaging & updated version.

### PR DESCRIPTION
**Pull request by kgaikwad**
1. Required absolute path instead of relative path for default CONFIG_FILE.
2. Changed data directory to /var/lib instead of /lib
3. Bump version to 0.0.5

### CODE REVIEW

**Comment by kgaikwad** [comment]
@gnurag , @swapab 
Please review changes which are required for packaging

**Comment by swapab** [comment]
LGTM

**Comment by kgaikwad** [comment]
@swapab , @gnurag,

Modified default value also for `backup_dir` in `lib/foreman_maintain/config.rb`.
Merging this PR.

**Comment by kgaikwad** [comment]
By mistake while merging chosen wrong option. So reverted the changes from master forcefully and again  merging it.

**Pull request merged**
