### PR TITLE
Fixes #28187 - Package manager feature refactoring

### PR DESCRIPTION
**Pull request by mbacovsky**
Package manager Feature was removed as it didn't provided much value
and was difficult to use form outside of definitions. The active manager
instance is now accessible via `ForemanMaintain.package_manager`
and is accessible from SystemHelpers concern. In definitions
it can be thus used directly as `package_manager`.

### CODE REVIEW

**Comment by mbacovsky** [comment]
I'm not sure what is wrong with the RM issues check, everything looks set properly

**Comment by kgaikwad** [comment]
Code wise looks good to me.
@jameerpathan111, could you please mind doing some testing?

**Comment by jameerpathan111** [comment]
@kgaikwad @mbacovsky I am getting following error.
```
# ./bin/foreman-maintain packages is-locked
undefined local variable or method `package_manager' for #<#<Class:0x000000025bcfc8>:0x000000025e74a8>

```
```
I, [2019-11-06 02:01:12-0500 #32680]  INFO -- : Running foreman-maintain command with arguments [["packages", "is-locked"]]
E, [2019-11-06 02:01:12-0500 #32680] ERROR -- : undefined local variable or method `package_manager' for #<#<Class:0x000000025bcfc8>:0x000000025e74a8> (NameError)
/root/foreman_maintain/lib/foreman_maintain/cli/packages_command.rb:56:in `execute'
/usr/share/gems/gems/clamp-1.1.2/lib/clamp/command.rb:63:in `run'
/usr/share/gems/gems/clamp-1.1.2/lib/clamp/subcommand/execution.rb:11:in `execute'
/usr/share/gems/gems/clamp-1.1.2/lib/clamp/command.rb:63:in `run'
/usr/share/gems/gems/clamp-1.1.2/lib/clamp/subcommand/execution.rb:11:in `execute'
/usr/share/gems/gems/clamp-1.1.2/lib/clamp/command.rb:63:in `run'
/root/foreman_maintain/lib/foreman_maintain/cli.rb:32:in `run'
/usr/share/gems/gems/clamp-1.1.2/lib/clamp/command.rb:132:in `run'
./bin/foreman-maintain:15:in `<main>'
I, [2019-11-06 02:01:12-0500 #32680]  INFO -- : foreman-maintain command finished with 1

```

**Comment by kgaikwad** [comment]
> ./bin/foreman-maintain packages is-locked
> undefined local variable or method `package_manager' for #<#<Class:0x000000025bcfc8>:0x000000025e74a8>

Thank you @jameerpathan111 for testing.
A method can be accessible via `ForemanMaintain.package_manager` inside command modules.

**Comment by mbacovsky** [comment]
@kgaikwad, @jameerpathan111, thanks, updated.

**Comment by kgaikwad** [comment]
Thank you @mbacovsky :ok_hand:

**Pull request merged**
