### PR TITLE
Fixes #23152 - validating repo error

### PR DESCRIPTION
**Pull request by upadhyeammit**
This fixes display issue of subscription-manager error message which is being displayed along with foreman-maintain check message.

### CODE REVIEW

**Comment by kgaikwad** [comment]
@upadhyeammit,
Rubocop is not happy!

**Comment by upadhyeammit** [comment]
@kgaikwad Its not happy because of https://github.com/theforeman/foreman_maintain/pull/193 modifications, should I make those rubocop changes in this PR itself ?

**Comment by kgaikwad** [comment]
@upadhyeammit,
ohh.. ok!
Then it would be good to have those changes in different PR instead of this PR.

**Comment by ntkathole** [comment]
@upadhyeammit i can still see same behaviour as mention in issue. Those statements are displayed in same line
```
Validate availability of repositories: 
- Validating availability of repositories for 6.4Consumer profile "f3b988f9-28f2-4230-af4a-fe4cf05143ca" has been deleted from the server. You can use command clean or unregister to remove local profile.
| Some repositories missing, calling `subscription-manager refresh`   [FAIL]    
Failed executing subscription-manager refresh, exit status 70:
 Unit f3b988f9-28f2-4230-af4a-fe4cf05143ca has been deleted
--------------------------------------------------------------------------------
```

**Comment by ntkathole** [comment]
Might be i was missing something...this works fine
```

Validate availability of repositories: 
/ Some repositories missing, calling `subscription-manager refresh`   [FAIL]    
Failed executing subscription-manager refresh, exit status 70:
 Unit c0fb3f2c-3967-4982-92d5-f553f88813c0 has been deleted
--------------------------------------------------------------------------------
```

**Comment by mbacovsky** [comment]
:+1: @upadhyeammit, thanks!

**Pull request merged**
