### PR TITLE
CLI for procedure invocation

### PR DESCRIPTION
**Pull request by mbacovsky**
This is draft of CLI for running Procedures. I tried to design it so it is usable for other resources (Checks, Scenarios?).  

Note: I found confusing that `description` as a class method describe the executable and as a instance variable is being used for logging of current action. I split that into `description` - static description of the check/procedure and `runtime_message` able to print instance data (defaulting to `description`). This change needs review.

Current state looks as follows:
```
[root@sat-test-rhel7 foreman_maintain]# ./bin/foreman-maintain -h
Usage:
    foreman-maintain [OPTIONS] SUBCOMMAND [ARG] ...

Parameters:
    SUBCOMMAND                    subcommand
    [ARG] ...                     subcommand arguments

Subcommands:
    health                        Health related commands
    upgrade                       Upgrade related commands
    procedure                     Run maintain procedures manually

Options:
    -h, --help                    print help
```
```
[root@sat-test-rhel7 foreman_maintain]# ./bin/foreman-maintain procedure -h
Usage:
    foreman-maintain procedure [OPTIONS] SUBCOMMAND [ARG] ...

Parameters:
    SUBCOMMAND                    subcommand
    [ARG] ...                     subcommand arguments

Subcommands:
    run                           Run maintain procedures manually
    run-by                        Run maintain procedures manually
    list-tags                     List tags used in procedures

Options:
    -h, --help                    print help
```
All the subcommands for run are dynamicaly generated from available procedures.
```
[root@sat-test-rhel7 foreman_maintain]# ./bin/foreman-maintain procedure run -h
Usage:
    foreman-maintain procedure run [OPTIONS] SUBCOMMAND [ARG] ...

Parameters:
    SUBCOMMAND                    subcommand
    [ARG] ...                     subcommand arguments

Subcommands:
    foreman-tasks-delete          delete tasks
    foreman-tasks-resume          resume paused tasks
    foreman-tasks-ui-investigate  investigate the tasks via UI
    hammer-setup                  setup hammer
    install-package               install packages(s)
    sync-plans-disable            disable active sync plans
    sync-plans-enable             re-enable sync plans

Options:
    -h, --help                    print help
```
Parameters are generated from procedure metadata
```
[root@sat-test-rhel7 foreman_maintain]# ./bin/foreman-maintain procedure run install-package -h
Usage:
    foreman-maintain procedure run install-package [OPTIONS]

Options:
    --packages PACKAGES           List of packages to install
    -y, --assumeyes               Automatically answer yes for all questions
    -h, --help                    print help
```
`run-by` supports filtering based on tags only as filtering with labels is replaced with `run <procedure-name>`. Passing params is not supported now and needs some decision to be made 
```
[root@sat-test-rhel7 foreman_maintain]# ./bin/foreman-maintain procedure run-by -h
Usage:
    foreman-maintain procedure run-by [OPTIONS]

Options:
    --tags tags                   Limit only for specific set of labels. (Use list-tags command to see available tags)
    -y, --assumeyes               Automatically answer yes for all questions
    -h, --help                    print help
```

### CODE REVIEW

**Comment by mbacovsky** [comment]
I had some questions during the design.

1/ First of all Do we want to expose procedures and checks at the first command level? They feel rather like internal components, so I'd  tend to hide them behind some command such as `extras`, `debug`, `expert` or similar leaving the 1st level for real life maintenance tasks such as `upgrade`, `backup`, `database`.

2/ There are no tags for procedures yet, are some going to be created?
3/ Does it make sense for the user to execute procedures by tags?
4/ Does it make sense for Checks?
5/ How do we want to pass arguments for the bulk Procedures/Checks run? What with the cinflicting params?
5.a/ --params "packages='package1,package2',foreman_db_ip='x.x.x.x'"
5.b/ dynamicaly created --packages "package1,package2" --foreman-db-ip "x.x.x.x"
6/ do we want similar approach for Scenarios?

Ideas are welcome!

**Comment by swapab** [comment]
`procedure` command looks good and could be useful in may ways.

> so I'd tend to hide them behind some command such as extras, debug, expert or similar leaving the 1st level for real life maintenance tasks such as upgrade, backup, database.

I agree with hiding it behind extras/expert or anything relevant.

> 2/ There are no tags for procedures yet, are some going to be created?

Yes, we can have tags for procedures(example: `proc-foreman-task` for all foreman-tasks related procedures)

> 3/ Does it make sense for the user to execute procedures by tags?

Yes, it does.

> 4/ Does it make sense for Checks?

Yes. But I suppose it would be based on the usability of the users. Some would comfortable with just checks and those in `advanced` mode can use procedures.

**Comment by iNecas** [comment]
1) Agreed, what about `advanced`?
2) +1 for counting on them
3) not a specific example but I can imagine such situation would occur
4) yes, unlinke procedures, it even doesn't seem for the checks to be hidden behind the advnaced command
5) for the beginning, just raising an error if a parameter is provided that can match multiple procedures
5b) - +1 for dynamically generated
6) not for scenarios, as there seems to be additional logic needed for special handling, that
needs to be passed in the command: you will see in the full upgrades PR

**Comment by kgaikwad** [comment]
1. Yeah, it is good idea to hide them behind command like debug, extras.
2. +1 to have tags for procedure.
3. Yes, If we have tags for procedures then any user can run any set of procedure using tags filter.

**Comment by swapab** [comment]
Can I contribute to this PR? or shall I just list down the changes which I feel relevant.

So basically I have following thoughts:

1/
```
## Include valid states in the help description

./bin/foreman-maintain advanced procedure run foreman-tasks-delete -h

--state STATE                 In what state should the task be deleted
```

2/ refactor https://github.com/theforeman/foreman_maintain/blob/master/definitions/features/foreman_tasks.rb#L133. define a constant or method for array and reuse it in 1/

**Comment by swapab** [comment]
Getting following error while running command
`foreman-maintain advanced procedure run foreman-tasks-resume`

```
sat63 :: ~/foreman_maintain ‹master› » ./bin/foreman-maintain advanced procedure run foreman-tasks-resume

Running ForemanMaintain::Scenario
================================================================================
resume paused tasks:                                                  [OK]
/opt/rh/rh-ruby22/root/usr/share/rubygems/rubygems/dependency.rb:315:in `to_specs': Could not find 'multi_json' (>= 1.8.4) among 150 total gem(s) (Gem::LoadError)
Checked in 'GEM_PATH=/opt/theforeman/tfm/root/usr/share/gems:/usr/local/rvm/gems/ruby-2.2.0@foreman_maintain:/usr/local/rvm/gems/ruby-2.2.0@global/usr/local/rvm/gems/ruby-2.2.0@foreman_maintain:/usr/local/rvm/gems/ruby-2.2.0@global', execute `gem env` for more information
	from /opt/rh/rh-ruby22/root/usr/share/rubygems/rubygems/specification.rb:1311:in `block in activate_dependencies'
	from /opt/rh/rh-ruby22/root/usr/share/rubygems/rubygems/specification.rb:1300:in `each'
	from /opt/rh/rh-ruby22/root/usr/share/rubygems/rubygems/specification.rb:1300:in `activate_dependencies'
	from /opt/rh/rh-ruby22/root/usr/share/rubygems/rubygems/specification.rb:1282:in `activate'
	from /opt/rh/rh-ruby22/root/usr/share/rubygems/rubygems/specification.rb:1314:in `block in activate_dependencies'
	from /opt/rh/rh-ruby22/root/usr/share/rubygems/rubygems/specification.rb:1300:in `each'
	from /opt/rh/rh-ruby22/root/usr/share/rubygems/rubygems/specification.rb:1300:in `activate_dependencies'
	from /opt/rh/rh-ruby22/root/usr/share/rubygems/rubygems/specification.rb:1282:in `activate'
	from /opt/rh/rh-ruby22/root/usr/share/rubygems/rubygems/core_ext/kernel_gem.rb:67:in `block in gem'
	from /opt/rh/rh-ruby22/root/usr/share/rubygems/rubygems/core_ext/kernel_gem.rb:66:in `synchronize'
	from /opt/rh/rh-ruby22/root/usr/share/rubygems/rubygems/core_ext/kernel_gem.rb:66:in `gem'
	from /usr/bin/hammer:22:in `<main>'
```

**Comment by mbacovsky** [comment]
@swapab, rebased + I still have to finish some tests. 

Re your comment on STATEs - it is good idea to enhance the help with the states. Adding param of type enum to the procedures might be the way to implement this. I'd prefer do to it in separate PR though to not heap up stuff in this one.
Re error - seems to be some issue with Hammer deps, I'm not able to reproduce.

**Comment by swapab** [comment]
Thanks @mbacovsky 

Can you also guide me through the `by-tag` command?
I am not able to run it on my setup.

```
sat63 :: ~/foreman_maintain ‹procedure_cli*› » ./bin/foreman-maintain advanced procedure by-tag
/usr/local/rvm/gems/ruby-2.2.0@foreman_maintain/gems/clamp-0.6.5/lib/clamp/command.rb:75:in `execute': you need to define #execute (RuntimeError)
	from /usr/local/rvm/gems/ruby-2.2.0@foreman_maintain/gems/clamp-0.6.5/lib/clamp/command.rb:67:in `run'
	from /usr/local/rvm/gems/ruby-2.2.0@foreman_maintain/gems/clamp-0.6.5/lib/clamp/subcommand/execution.rb:11:in `execute'
	from /usr/local/rvm/gems/ruby-2.2.0@foreman_maintain/gems/clamp-0.6.5/lib/clamp/command.rb:67:in `run'
	from /usr/local/rvm/gems/ruby-2.2.0@foreman_maintain/gems/clamp-0.6.5/lib/clamp/subcommand/execution.rb:11:in `execute'
	from /usr/local/rvm/gems/ruby-2.2.0@foreman_maintain/gems/clamp-0.6.5/lib/clamp/command.rb:67:in `run'
	from /usr/local/rvm/gems/ruby-2.2.0@foreman_maintain/gems/clamp-0.6.5/lib/clamp/subcommand/execution.rb:11:in `execute'
	from /usr/local/rvm/gems/ruby-2.2.0@foreman_maintain/gems/clamp-0.6.5/lib/clamp/command.rb:67:in `run'
	from /usr/local/rvm/gems/ruby-2.2.0@foreman_maintain/gems/clamp-0.6.5/lib/clamp/command.rb:132:in `run'

```

**Comment by mbacovsky** [comment]
@swapab this happens, when there are no tags on procedures so there are no subcommands generated. I'll fix it.

**Comment by mbacovsky** [comment]
The tests are finally green, let me know when it is ready to merge and can do some manual squashing to preserve @swapab's credits in his commit.

**Comment by swapab** [comment]
Was able to run all procedures successfully.
This patch is good to merge.

**Comment by mbacovsky** [comment]
Great, thanks @swapab, I'll do the squash and update the PR

**Comment by iNecas** [comment]
The PR has still WIP in title. Should I go ahead and merge it?

**Comment by mbacovsky** [comment]
@iNecas fixed, lets merge it please

**Comment by iNecas** [comment]
Done, thanks @mbacovsky and @swapab

**Pull request merged**
