### PR TITLE
Fixes #34937 - Simplify self-upgrade mechanism

### PR DESCRIPTION
**Pull request by upadhyeammit**

### CODE REVIEW

**Comment by evgeni** [comment]
We had added tests, which now can be removed again (test/definitions/scenarios/self_upgrade_test.rb)

**Review by evgeni — APPROVED** [review]
ACK pending test cleanup

**Review by evgeni — APPROVED** [review]
all the nice tests that I have written :crying_cat_face:

**Comment by upadhyeammit** [comment]
Thanks for review @evgeni , merging this now.

**Pull request merged**
