### PR TITLE
Refs #33346 - limit switchover run below Katello 4.0 version

### PR DESCRIPTION
**Pull request by upadhyeammit**

### CODE REVIEW

**Comment by upadhyeammit** [comment]
as switchover procedure wont be available because of confine block the add_step_with_context wont work from scenario. I added unless condition there too.
@jlsherrill  request to check, thank you!

**Comment by upadhyeammit** [comment]
and I also think we can skip whole `pulp3_switchover_steps` as per the unless condition?

**Comment by jlsherrill** [comment]
i agree, we could put the whole section in that unless block that starts/stops the services too

**Comment by upadhyeammit** [comment]
@jlsherrill thanks for the feedback, merging this!

**Pull request merged**
