### PR TITLE
Add GenerateReportJob to list of excluded actions

### PR DESCRIPTION
**Pull request by adamruzicka**
CC @shimshtein

### CODE REVIEW

**Comment by ShimShtein** [comment]
While this is enough for the current issue, let's add all tasks that are repeatable:
```
InsightsCloud::Async::InsightsFullSync
InsightsCloud::Async::InsightsGenerateNotifications
InsightsCloud::Async::InsightsResolutionsSync 
InsightsCloud::Async::InsightsRulesSync
InventorySync::Async::InventoryFullSync
InventorySync::Async::InventoryHostsSync
InventorySync::Async::InventorySelfHostSync
```

**Comment by ShimShtein** [comment]
Sorry, but I have missed another folder with tasks:
```
ForemanInventoryUpload::Async::QueueForUploadJob
ForemanInventoryUpload::Async::UploadReportJob
```

I think it's the last one

**Comment by adamruzicka** [comment]
I added everything I found by running this in rh cloud's repo.
```
grep -R 'ForemanTasks.a?sync_task\(.*\)' -P .  | grep '\(.*\)' -o -P | awk -F, ' { print $1 } ' | tr -d '()' | sort | uniq
```

**Comment by ShimShtein** [comment]
:+1:  ACK from me

**Review by ehelms — APPROVED** [review]

**Pull request merged**
