### PR TITLE
Fixes #20898 - removed params from runtime_message in metadata.rb

### PR DESCRIPTION
**Pull request by kgaikwad**

### CODE REVIEW

**Comment by iNecas** [comment]
Tests are failing now, probably due to issues that were introduced by merging two last PRs at the same time. @kgaikwad would you mind updating that here?

**Comment by kgaikwad** [comment]
@iNecas , 
Done. Pulled new changes.

**Comment by iNecas** [comment]
Thanks @kgaikwad 

@gnurag we can release a new version now

**Comment by gnurag** [comment]
Thanks @iNecas, will go ahead with it.

**Pull request merged**
