### PR TITLE
Fixes #22976, #22977 - foreman-installer doesnt take --upgrade

### PR DESCRIPTION
**Pull request by sean797**
and katello-installer doesn't exist anymore

### CODE REVIEW

**Comment by iNecas** [comment]
Don't forget, that this is meant to be used with katello upstream, where katello-installer is still pretty common and active https://github.com/Katello/katello-installer. A redmine issue against http://projects.theforeman.org/projects/foreman-maintain/issues/new is also appreciated.

**Comment by iNecas** [comment]
Scratch that, I was too fast with the comment: on the other hand, since we still target satellite 6.1 (at least in theory), we should still keep `katello-installer` option there.

**Comment by sean797** [comment]
Hows that @iNecas ? Thanks!

**Comment by iNecas** [comment]
Much better, ready for testing @ntkathole

**Comment by iNecas** [comment]
Well, ready for testing after rebase, as there is a conflict at the moment

**Comment by iNecas** [comment]
Thanks @sean797  and @ntkathole

**Pull request merged**
