### PR TITLE
Fixes #34278 - only stop services if available

### PR DESCRIPTION
**Pull request by upadhyeammit**

### CODE REVIEW

**Comment by vsedmik** [comment]
ACK, fixed the issue - puppet can be disabled on the Capsule now:
```
[root@capsule ~]# foreman-maintain plugin purge-puppet
Running Remove Puppet feature
================================================================================
Remove Puppet feature:                                                [OK]
--------------------------------------------------------------------------------

[root@capsule ~]# systemctl status puppetserver
Unit puppetserver.service could not be found.
[root@capsule~]# curl https://$(hostname):9090/features
["container_gateway","dynflow","logs","pulpcore","registration","ssh","templates"]
```

**Comment by upadhyeammit** [comment]
@ezr-ondrej request to review.

**Review by ezr-ondrej — APPROVED** [review]
:facepalm: me ... Thanks @upadhyeammit for the fix! :+1:

**Review by ezr-ondrej — APPROVED** [review]
:+1:

**Pull request merged**
