### PR TITLE
Fixes #19942 - upstream upgrade - 1.14 -> 1.15 -> 1.16

### PR DESCRIPTION
**Pull request by swapab**

### CODE REVIEW

**Comment by iNecas** [comment]
/me needs to test this, but before I start, there is travis failing currently

**Comment by swapab** [comment]
Successfully upgraded foreman instance from `1.14 to 1.15 to 1.16` after adding respective fixes(confine blocks) for:
http://projects.theforeman.org/issues/21588
http://projects.theforeman.org/issues/21589

The upgraded foreman pacakge versions were as follows:
foreman-1.14.3-1.el7.noarch
foreman-1.15.6-1.el7.noarch
foreman-1.16.0-0.2.RC2.el7.noarch

Though there are no checks which can on foreman standalone instance. Can we think of any such check(s)?

Also, checks related to 'foreman-tasks' could not run because we are confining them to `foreman-tasks` package:

```
      check_min_version('ruby193-rubygem-foreman-tasks', '0.6') ||
        check_min_version('tfm-rubygem-foreman-tasks', '0.7')
```

Should we also check for package `tfm-rubygem-dynflow` so that checks related to foreman-tasks runs on upstream and what should be the minimum version for it?

**Dynflow** check might have 1 exception though(table `foreman_tasks_tasks`) so need to ensure `foreman_tasks` feature performs actions on the table only if it exists.

This way we can enable foreman-tasks check for foreman only instances.

**Comment by swapab** [comment]
> Should we also check for package tfm-rubygem-dynflow so that checks related to foreman-tasks runs on upstream and what should be the minimum version for it?

Created an issue for this: http://projects.theforeman.org/issues/21610

**Comment by iNecas** [comment]
Have not tested, but codewise looks good. I'm ok with testing this to get this actually to hands of people.

**Comment by swapab** [comment]
@iNecas Is this PR good to merge?

**Comment by kgaikwad** [comment]
@swapab , could you please update this branch with latest master?

**Comment by swapab** [comment]
@kgaikwad Rebased :+1:

**Comment by ntkathole** [comment]
Looks good! I am able to upgrade standalone foreman instance from 1.14 > 1.15 > 1.16. For checks, faced above issues mentioned by @swapab .
Note:
1. Performing upgrade from 1.14 do not ask confirmation from user to perform migration once all check passed.
2. yum update does not honour -y option provided while performing upgrade run -y.

**Comment by kgaikwad** [comment]
Closing in favor of #230.

**Pull request closed without merging**
