### PR TITLE
Fixes #35261 - Run procedure FixPulpcoreArtifactOwnership during 6.11 upgrade

### PR DESCRIPTION
**Pull request by sjha4**
Correct permissions of artifacts directory with FixPulpcoreArtifactOwnership procedure automatically during 6.11 upgrade.

### CODE REVIEW

**Comment by upadhyeammit** [comment]
Can this be done on Capsule as well?

**Comment by sjha4** [comment]
@upadhyeammit : Updated to also run on capsule upgrade. 👍🏼

**Comment by upadhyeammit** [comment]
@sjha4 few more questions before we can merge,
1. This will only run when 6.10 to 6.11 upgrade will happen and not when 6.11.z upgrades. So in that case should we also do this for 6.11.z scenarios of Satellite and Capsule?
2. However I feel if the issue is there on 6.11 mostly users will correct it first before upgrade? because basic repo sync is failing?

**Comment by sjha4** [comment]
Added the procedure to 6.11.z scenarios for cases where the 6.11 upgrade missed the step. 👍🏼

**Review by ianballou — APPROVED** [review]
Looks fine to me!

**Pull request merged**
